version: '3'

services:
    php:
      build: './docker/php/'
      volumes:
        - ./app/:/var/www/html/
      networks:
        - symfony

    nginx:
      container_name: nginx
      image: nginx:stable-alpine
      ports:
        - '8077:88'
      volumes:
        - ./app:/var/www/html
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - database
      networks:
        - symfony

    database:
      container_name: 'mysql'
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: symfony
      ports:
        - "3306:3306"
      networks:
        - symfony

networks:
  symfony: